//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jQueryAjaxInAsp.NETMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hsn_table
    {
        public long id { get; set; }
        public string product_id { get; set; }
        public string file_id { get; set; }
        public string prod_desc { get; set; }
        public string ref_files_path { get; set; }
        public int year { get; set; }
        public long estimated_eu_taric { get; set; }
        public long estimated_eu_en { get; set; }
        public long estimated_us_htsus { get; set; }
        public long estimated_us_schedule_b { get; set; }
        public long estimated_china_hsn { get; set; }
        public long estimated_india_hsn { get; set; }
        public long estimated_turkey_hsn { get; set; }
        public long estimated_sa_tariff_code { get; set; }
        public Nullable<long> actual_eu_taric { get; set; }
        public Nullable<long> actual_eu_en { get; set; }
        public Nullable<long> actual_us_htsus { get; set; }
        public Nullable<long> actual_us_schedule_b { get; set; }
        public Nullable<long> actual_china_hsn { get; set; }
        public Nullable<long> actual_india_hsn { get; set; }
        public Nullable<long> actual_turkey_hsn { get; set; }
        public Nullable<long> actual_sa_tariff_code { get; set; }
    }
}
